# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 563287728416b94ffac55d57557db61edbd6273556d69dc883f64d55006baea4af9dde2fca8399937ddc75b7d42e415b21ccd95851f6bddd209899b9448ac759

test:
  secret_key_base: 2faa66c73d87aa8f15aadea9b4805f86c3f9295efc415f3348052512704bd8fdce1f31c33f527e7ada8db9b6dad2e95cb3987ea8e6c065ae08141770df58f2ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
